---
- hosts: server
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker
          - docker-compose
        state: present
    - name: Login DockerHub
      shell: docker login -u "{{DOCKER_USERNAME}}" -p "{{DOCKER_PASSWORD}}"
    - name: Copy file
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu/
    - name: Restart docker-compose
      shell: |
          sudo docker-compose stop
          sudo docker-compose rm -f
          sudo docker-compose pull
          sudo docker-compose up -d
...
  